const redisData = {
    'seoul': 0,
    'gygg': 0,
    'incheon': 0,
    'gangwon': 0,
    'chungnam': 0,
    'chungbuk': 0,
    'daejeon': 0,
    'jeonbuk': 0,
    'jeonnam': 0,
    'gwangju': 0,
    'jeju': 0,
    'gyeongbuk': 0,
    'gyeongnam': 0,
    'daegu': 0,
    'ulsan': 0,
    'busan': 0,
    'sejong':0,
};
const locationTable = {
    'seoul': '서울특별시',
    'gygg': '경기도',
    'incheon': '인천광역시',
    'gangwon': '강원',
    'chungnam': '충청남도',
    'chungbuk': '충청북도',
    'daejeon': '대전광역시',
    'jeonbuk': '전라북도',
    'jeonnam': '전라남도',
    'gwangju': '광주광역시',
    'sejong' : '세종특별자치시',
    'jeju': '제주특별자치도',
    'gyeongbuk': '경상북도',
    'gyeongnam': '경상남도',
    'daegu': '대구',
    'ulsan': '울산',
    'busan': '부산',
};

module.exports = {redisData,locationTable};